### ISSUE TITLE
Migrated my workflow but still seeing the old one

### ISSUE THREAD

**Issue by moomerman** [actions/migrate#26]
Hi I've just migrated my workflow as per the docs. I also deleted the old main.workflow and re-opted-in for the beta, even though it just said I was already in it.  Here is the workflow the migration created:

![image](https://user-images.githubusercontent.com/23323/62735532-496cce80-ba23-11e9-9387-69bba7f3dd7b.png)

But when I visit the `Actions` tab I'm seeing the old workflow that appears to be stuck (for 2 days!) - I can't cancel it or do anything else, and the new workflow isn't running even though I expected it to when I committed it:

![image](https://user-images.githubusercontent.com/23323/62735602-6c977e00-ba23-11e9-99b2-7b67d8a86a32.png)

Thanks! ❤️

**Comment by lbrownell-gpsw** [comment]
Same problem as above...

 ...But about that re-opt-in for the beta:  Our organization was in the pre-CI/CD Actions beta.  When I go to the opt-in page, it presents me with a button to pick an organization.  When I pick the aforementioned already Action Beta enrolled org, it just says "You're already in the beta".  Is that all that's expected?

Thanks, looking forward to trying your build system.

**Comment by pcolby** [comment]
Seeing the same problem.  Just adding: for me, new repos (that didn't have any old-style HCL workflows yet) also fail to see the any new YAML-style workflows, and clicking the "Create a new workflow" button is attempting to create `.github/main.workflow` (even though I have `.github/workflows/*.yml` files already).  So the issue it not specific to the migration existing workflows, but even adding new ones is broken currently.

Can't wait till they fix it... keen to play! :)

**Comment by skx** [comment]
The upgrade page says this:

> If you participated in the limited public beta and created workflows with the HCL syntax GitHub Actions, you will need to upgrade to the new limited public beta that uses YAML syntax. When your repository is eligible to upgrade, you'll see an invitation in your repository. You must accept the invitation before you can use the new limited public beta.

Implying there is a second beta, to which we have to await an invitation.    We'll see.

**Comment by mscoutermarsh** [comment]
Sorry for the confusion here. We're rolling out the upgrade invites ASAP to people in the existing beta (we're monitoring for any scaling issues as we add more people).

You'll see a notice on your Actions tab when it's available for your account. Excited to have you all onboard ❤️

**Comment by simonhaenisch** [comment]
> ASAP

Are we talking about hours, days, or weeks? 🤓 Indeed confusing, because you'd expect to be in the beta once you got into the beta.

**Comment by glyph** [comment]
I saw the invitation to upgrade, dismissed it because I was in the middle of waiting for an existing workflow to run, then went through the upgrade steps - now I can't get the invitation back.  Is there a setting hidden somewhere that I'm not seeing?

**Comment by barkerja** [comment]
Echoing what others have already stated here. The rollout has been confusing for those already in the beta program. I spent an hour or two migrating my old workflows to the new structure then tried to figure out _why_ the new workflows weren't working.

Updating the actions beta page to make note of the **new beta** would likely go a long ways. Simply indicating you're already part of the actions beta when there's a new one is very confusing.

**Comment by timruffles** [comment]
Thanks for trying the new beta, and reporting that the messaging could have been better!

I'll add a note to the tool to make this clearer. Closing as unrelated to the migrate tool.

**Comment by simonhaenisch** [comment]
Can you keep us up to date though, please? Still not seeing a notification in the actions tab of my repo.

**Comment by cho0o0** [comment]
If you click the "Sign up for the beta" button you will see "GitHub Actions is already enabled on your account!" but actually it is not for the latest version. It was really confusing.

**Comment by mscoutermarsh** [comment]
We're working on updating the UI today in the Actions tab to make this less confusing. Will update here when it's shipped.

**Comment by cho0o0** [comment]
@mscoutermarsh Great! Also looking forward to trying the new version soon.

**Comment by mscoutermarsh** [comment]
Hi all,

On your Actions tab, take a look at the top right. You'll now see a message about if you can upgrade yet.

If you're able to upgrade, you'll be able to click a button to opt-in to the new workflow format.

We're pushing out invitations as fast as we can (we're watching for any scaling issues as more people join).

![image](https://user-images.githubusercontent.com/155044/63067514-33985700-bec4-11e9-8b43-4503ced57fb0.png)
