### ISSUE TITLE
Checkout fails after migration

### ISSUE THREAD

**Issue by Bogdanp** [actions/migrate#30]
I have converted this workflow:

https://github.com/Bogdanp/deta/blob/master/.github/main.workflow

into:

https://github.com/Bogdanp/deta/blob/b3910e064ba4e3456930bd71b6ff3cc9b8738abb/.github/workflows/push.yml

and my run is failing with

```
fatal: could not read Username for 'https://github.com': terminal prompts disabled
```

details here:

https://github.com/Bogdanp/deta/runs/190390227

**Comment by Bogdanp** [comment]
Re-running the workflow seems to have fixed the problem. I'm going to leave this open in case it helps, though.

**Comment by timruffles** [comment]
Thanks! You'll get prompter help re runtime issues via standard support channels.
