### ISSUE TITLE
Migration switches schedule event to "schedules"

### ISSUE THREAD

**Issue by lannonbr** [actions/migrate#36]
When you have a HCL workflow that has a workflow with a "schedule" trigger, it converts it to "schedules". This worked until this past Monday when these new YML workflows with "schedules" just don't trigger anymore. I switched it to "schedule" and it was fine again.

This seems to be the line that converts "schedule" to "schedules" in the source of the migrate cli:

https://github.com/actions/migrate/blob/ee70e1a2c9ce5321408891da87604ab98ec79205/converter/convert.go#L169-L181

Is this an intended or should it be "schedule" in HCL -> "schedule" in YML?

**Comment by ain** [comment]
Reproduced. Still happens in the latest release of https://github.com/actions/migrate/releases/tag/2019-08-06%4020-47

**Comment by iheanyi** [comment]
Hey @ain and @lannonbr, I've merged a fix in and cut a new release could you all give it a whirl and confirm that this has been fixed?  Thanks!
